#!/bin/bash
#SBATCH --gres=gpu:1 
#SBATCH --mem=18g
##SBATCH --nodelist=compute-0-7
#SBATCH -t 0

#export PYTHONPATH="$(pwd)"
#export CUDA_VISIBLE_DEVICES="3"

#DDIR=/home/hyhieu/xinyiw/ScoreNMT/
DDIR=/home/xinyiw1/ScoreNMT/

python3.6 src/rl_main.py \
  --clean_mem_every 5 \
  --reset_output_dir \
  --output_dir="outputs_sSEED/hs-cosine-lan_dist_DATA_IL/" \
  --train_src_file_list "$DDIR"data/LAN_eng/ted-train.mtok.spm8000.LAN \
  --train_trg_file_list  "$DDIR"data_moses/LAN_eng/ted-train.mtok.spm8000.eng \
  --dev_src_file_list  "$DDIR"data/IL_eng/ted-dev.mtok.spm8000.IL \
  --dev_trg_file_list  "$DDIR"data_moses/IL_eng/ted-dev.mtok.spm8000.eng \
  --dev_ref_file_list  "$DDIR"data_moses/IL_eng/ted-dev.mtok.eng \
  --dev_file_idx_list  "0" \
  --src_vocab_list  "$DDIR"data/LAN_eng/ted-train.mtok.spm8000.LAN.vocab \
  --src_char_vocab_from  "$DDIR"data/LAN_eng/ted-train.mtok.LAN.char4vocab \
  --char_ngram_n 4 \
  --src_char_vocab_size="8000" \
  --trg_vocab  "$DDIR"data_moses/eng/ted-train.mtok.spm8000.eng.vocab \
  --lang_file langs_DATA.txt \
  --lan_dist_file "$DDIR"ted-train-vocab.mtok.sim-ngram.graph \
  --base_lan "IL" \
  --d_word_vec=128 \
  --d_model=512 \
  --log_every=50 \
  --eval_every=2500 \
  --ppl_thresh=THRESH \
  --merge_bpe \
  --eval_bleu \
  --batcher='word' \
  --batch_size 1500 \
  --raw_batch_size 1 \
  --lr_dec 1.0 \
  --lr 0.001 \
  --lr_q 0.0001 \
  --refresh_base_grad=0 \
  --refresh_all_grad=1 \
  --n_train_epochs=20 \
  --dropout 0.3 \
  --max_len 250 \
  --agent_subsample_line 16000 \
  --train_score_episode=100 \
  --print_every 50 \
  --train_score_every=50000 \
  --record_grad_step=100 \
  --data_name="DATA" \
  --d_hidden 32 \
  --adam_raw_grad=0 \
  --reward_scale=0.01 \
  --grad_dist="cosine" \
  --cuda \
  --imitate_episode 2 \
  --imitate_type "heuristic" \
  --actor_type="base" \
  --feature_type="lan_dist" \
  --add_bias=0 \
  --scale_0=0.5 \
  --scale_1=1.0 \
  --seed SEED
