#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --mem=12g
##SBATCH --nodelist=compute-0-7
#SBATCH -t 0

#export PYTHONPATH="$(pwd)"
#export CUDA_VISIBLE_DEVICES="2"

python3.6 src/translate.py \
  --model_dir="outputs_VERSION/NAME/" \
  --test_src_file_list data/IL_eng/ted-test.mtok.IL \
  --test_trg_file_list data/IL_eng/ted-test.mtok.eng \
  --test_file_idx_list "0" \
  --cuda \
  --merge_bpe \
  --beam_size=5 \
  --poly_norm_m=1 \
  --max_len=200 \
  --out_file="ted-test-b5m1" 
